import request from './request'

export const deal = ({
  locationinfoId,
  queNum,
  wtxq,
  userId,
  dealProgress,
  dealDuration,
  submitNickName,
  longitude,
  latitude,
  imageWtyj,
  imageWtjj1,
  imageWtjj2,
  imageWtjj3,
  imageWtyj_Wc,
  imageWtjj1Wc,
  imageWtjj2Wc,
  imagetjj3Wc,
}) =>
  request({
    url: `/gas/dealquestion/deal`,
    method: 'post',
    data: {
      locationinfoId,
      queNum,
      wtxq,
      userId,
      dealProgress,
      dealDuration,
      submitNickName,
      longitude,
      latitude,
      imageWtyj,
      imageWtjj1,
      imageWtjj2,
      imageWtjj3,
      imageWtyj_Wc,
      imageWtjj1Wc,
      imageWtjj2Wc,
      imagetjj3Wc,
    },
  })
